### PR TITLE
Update some minor things to make it work

### PR DESCRIPTION
**Pull request by mkoderer**

### CODE REVIEW

**Comment by VRevol** [comment]
Hello,
I end up with the same changes for the requirements :)
I would also need the docker container https://hub.docker.com/r/maxandersen/sonos_exporter updated as I am running it on a synology with docker-compose.

@maxandersen Would be very helpful if you could update it 👍

**Comment by maxandersen** [comment]
Merged. Should be automatically picked up in docker hub build. If not I can force it.

**Comment by VRevol** [comment]
> Merged. Should be automatically picked up in docker hub build. If not I can force it.

Hello,
I was checking on docker hub but it seems it is still the old version from 2 years ago :)
It is not urgent, but if you got time, could you check the build pipeline that publish it ?

Thanks a lot

BTW, I like very much your internet_monitoring too ;) Thanks for this 👍

**Comment by mkoderer** [comment]
@VRevol I pushed my container to docker.io/dreamrocker/sonosexporter
Hope this works since I am on armv7. Let me open another PR and include my Dockerfile if this helps

**Comment by mkoderer** [comment]
https://github.com/maxandersen/sonos_exporter/pull/2

**Comment by VRevol** [comment]
> @VRevol I pushed my container to docker.io/dreamrocker/sonosexporter
> Hope this works since I am on armv7. Let me open another PR and include my Dockerfile if this helps

Unfortunately I am running this on a synology which is not armv7.
Plus, it seems I cannot find your dreamrocker/sonosexporter anywhere... is it possible that this repo is private ?

I end up creating my own dockerhub repo to both get experience on it, and make a linux64 version available:
vrevol/sonos_exporter
What's strange is that when not logged in, I don't see it...

**Comment by mkoderer** [comment]
Somehow the link was wrong:
https://hub.docker.com/r/dreamrocker/sonosexporter

`docker pull dreamrocker/sonosexporter:latest`

**Comment by maxandersen** [comment]
hi @mkoderer and @VRevol - sorry for not noticing your  comments.

the active branch was actually not master but dockerized which i now renamed to main and set as default plus fixed the auto publishing - dockerhub needed github reconnet

**Pull request merged**
